environment:
  PYTHON: "C:\\Python37-x64"

install:
  - "%PYTHON%\\python.exe -m pip install --upgrade pip"
  - "%PYTHON%\\Scripts\\pip install -r requirements.txt"
  - "%PYTHON%\\python.exe scripts\\download_icons.py"

build_script:
  - ps: scripts\\pyinstaller.ps1
  - "move dist\\main my_todo_win32_x64"
  - 7z a my_todo_win32_x64.zip my_todo_win32_x64

artifacts:
  - path: my_todo_win32_x64.zip
